# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "order_app"

development:
  <<: *common
  brokers:
    - kafka:29092

test:
  <<: *common
  brokers:
    - kafka:29092

production:
  <<: *common
  brokers:
    - kafka1.myapp.com:29092
    - kafka2.myapp.com:29092
    - kafka3.myapp.com:29092
